// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// NotificationProcessor is an autogenerated mock type for the NotificationProcessor type
type NotificationProcessor struct {
	mock.Mock
}

// Process provides a mock function with given fields: ctx
func (_m *NotificationProcessor) Process(ctx context.Context) {
	_m.Called(ctx)
}

// NewNotificationProcessor creates a new instance of NotificationProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationProcessor {
	mock := &NotificationProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
