// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SmtpService is an autogenerated mock type for the SmtpService type
type SmtpService struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: ctx, content, to
func (_m *SmtpService) SendEmail(ctx context.Context, content string, to string) error {
	ret := _m.Called(ctx, content, to)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, content, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSmtpService creates a new instance of SmtpService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSmtpService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SmtpService {
	mock := &SmtpService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
